version: "2.3"
services:
  test:
    # build: "."
    image: node:slim
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      DATA_DIR: /data/
      BOT_TOKEN: NDQ1OTAxNDczMTU1NTE0Mzc4.DeWIZA.h5oLKk9yTAos4ne0wcHnK3ebJIk
    working_dir: /app
    entrypoint: bash -c "yarn & yarn debug"
